### ISSUE TITLE
search returning empty response

### ISSUE THREAD

**Issue by chz101** [l2studio/iqdb-api#2]
Hi, I came across this library and would love to use it. However, I'm running into issues when calling the search function:
```javascript
import * as iqdb from '@l2studio/iqdb-api'
import * as fs from 'fs';
import * as process from 'process';

try {
	var Response = iqdb.search(fs.readFileSync('Check/test.jpg'));
}
catch(e){
	console.error(e.message);
}

console.log(`${Response.searched}`);
const newData = { Response }
console.log(JSON.stringify(newData));
```

returns 
```
undefined
{"Response":{}}
```
Can you spot any issues with my code that makes the function call not work? I'm fairly new to scripting languages so I'm not sure what's going wrong.

Thank you

**Comment by lgou2w** [comment]
The `search` is asynchronous and returns a `Promise<SearchResponse>`.

Should be:
```ts
// Wrap your code with self-invoking async function
;(async () => {
  try {
    // Must wait for promise
    var Response = await iqdb.search(fs.readFileSync('Check/test.jpg'));
    // Print response
    console.log(Response);
  }
  catch(e){
    console.error(e.message);
  }
})();

// Or use the then and catch call chain
iqdb
  .search(fs.readFileSync('Check/test.jpg'))
  .then((response) => console.log(response))
  .catch((e) => console.error(e.message))
```

See [`Promise`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) documentation.

**Comment by chz101** [comment]
Ah awesome, didn't expect the function to be asynchronous. Looks like everything is working perfectly now. 
Thanks for all your help!
